spring:
  application:
    name: fraud-service

  kafka:
    consumer:
      group-id: fraud-service
      auto-offset-reset: earliest

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  topics:
    transaction-created: transaction.created.v2
