server:
  port: 8081

spring:
  application:
    name: fraud-service

  kafka:
    bootstrap-servers: localhost:9092

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  topics:
    transaction-created: transaction.created.v2
